### ISSUE TITLE
Not unregistering exited processes

### ISSUE THREAD

**Issue by ZGF4** [ostinelli/syn#29] opened 2016-11-14 01:09 UTC
I'm having an issue where it seems like syn is not unregistering processes when they exit.  I'm able to get a pid from `syn:whereis_name` but if I try to send messages to the result I get a `no such process` error.  I've verified the process indeed does not exist.

Any idea?

**Comment by ostinelli** [comment] 2016-11-14 10:23
Syn is eventually consistent. Even if it's fast, it can still take a little while in a distributed system have a process be unregistered (you can find some benchmarks [here](http://www.ostinelli.net/an-evaluation-of-erlang-global-process-registries-meet-syn/)). Is this the case?

If not, then I'd need to know more and have a way to reproduce, because I've not seen this behavior and would need a fix.

PS: I assume that you are referring to `syn:find_by_key/1,2` method, there is no `whereis_name` method.

**Comment by dax0** [comment] 2016-11-14 14:42
The process actually never ends up being unregistered until I unregister it
manually.  I haven't yet been able to reproduce it consistently but I'll
try to dig into it.  The scenario it's happening under is a GenServer stops
itself but it doesn't get unregistered

On Mon, Nov 14, 2016, 5:23 AM Roberto Ostinelli <notifications@github.com>
wrote:

Syn is eventually consistent. Even if it's fast, it can still take a little
while in a distributed system have a process be unregistered (you can find
some benchmarks here
<http://www.ostinelli.net/an-evaluation-of-erlang-global-process-registries-meet-syn/>).
Is this the case?

If not, then I'd need to know more and have a way to reproduce, because
I've not seen this behavior and would need a fix.

PS: I assume that you are referring to syn:find_by_key/1,2 method, there is
no whereis_name method.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ostinelli/syn/issues/29#issuecomment-260299195>, or mute
the thread

**Comment by ostinelli** [comment] 2016-11-14 16:13
Again: What functions are you using? How do you "manually unregister it"? Without details there isn't much help that I can provide. :)

**Comment by dax0** [comment] 2016-11-14 16:38
Sorry for the sparse information I'm going to debug more and come back with better information.  I'm on 1.5 but I'm going to try 1.6 and by manually unregister I meant calling `syn:unregister`

**Comment by malmovich** [comment] 2016-12-04 20:06
I have the exact same issue and are also using syn:register and syn:find_by_key. It seems to happen when there are multiple processes each on different nodes that tries to register a specific name

**Comment by malmovich** [comment] 2016-12-04 20:45
I have the exact same issue and are also using `syn:register` and `syn:find_by_key`. It seems to happen when there are multiple processes, each living on different nodes, that is trying to register the same key simultaneously.  When it gets into the error state, it can be resolved by calling `syn:unregister`, just as dax0 explained.
The setup is a three node cluster running syn v1.6 (also tried with 1.5) and OTP 19.1 (also tried with 18.3), where two of the nodes had registered the same pid and the third had a different pid - none of them alive. 
I can reproduce this on my setup by spawning multiple pairs of processes living on two different nodes, competing to register the same key. However, not consistently.

**Comment by ostinelli** [comment] 2016-12-21 11:23
@malmovich mnesia will send a message when it gets inconsistent, which is what you are referring to. When it does, syn gets the message and it resolves the conflicts, see [here](https://github.com/ostinelli/syn/blob/1.6.0/src/syn_consistency.erl#L123).

Are you seeing any messages in the logs?

**Comment by ostinelli** [comment] 2017-01-03 15:23
@dax0 and @malmovich did you get a chance to look into this (logs, etc)? Thank you.

**Comment by ostinelli** [comment] 2017-02-28 09:42
Closing due to no activity.

**Closed by ostinelli** 2017-02-28 09:42 UTC
